# Generated by Django 2.1.5 on 2019-02-09 13:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreFields',
            fields=[
                ('whoweare_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.TextField(verbose_name='Title of the page *')),
                ('pathlist', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='Path list *')),
                ('firstsectionabouttitles', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='First Section pages titles *')),
                ('firstsectionaboutURLS', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='First Section pages URLS *')),
                ('secondsectioncompanyoverviewtitle', models.TextField(verbose_name='Second Section company overview title *')),
                ('secondsectioncompanyoverviewdescription', models.TextField(verbose_name='Second Section company overview description *')),
                ('thirdsectionenterprisetitle', models.TextField(verbose_name='Third Section enterprise title *')),
                ('thirdsectionenterprisedescription', models.TextField(verbose_name='Third Section enterprise description *')),
                ('fourthsectionmissionvisionvaluestitles', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=183, size=3, verbose_name='Fourth Section mission vision and values titles *')),
                ('fourthsectionmissionvisionvaluesdescriptions', django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=1503, size=3, verbose_name='Fourth Section mission vision and values descriptions *')),
            ],
        ),
    ]
