# Generated by Django 2.1.5 on 2019-02-09 14:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whowearefields',
            name='firstsectionaboutURLS',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=427, null=True, size=7, verbose_name='First Section pages URLS *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='firstsectionabouttitles',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=427, null=True, size=7, verbose_name='First Section pages titles *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='fourthsectionmissionvisionvaluesdescriptions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=1503, null=True, size=3, verbose_name='Fourth Section mission vision and values descriptions *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='fourthsectionmissionvisionvaluestitles',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=183, null=True, size=3, verbose_name='Fourth Section mission vision and values titles *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='secondsectioncompanyoverviewdescription',
            field=models.TextField(blank=True, null=True, verbose_name='Second Section company overview description *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='secondsectioncompanyoverviewtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Second Section company overview title *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='thirdsectionenterprisedescription',
            field=models.TextField(blank=True, null=True, verbose_name='Third Section enterprise description *'),
        ),
        migrations.AlterField(
            model_name='whowearefields',
            name='thirdsectionenterprisetitle',
            field=models.TextField(blank=True, null=True, verbose_name='Third Section enterprise title *'),
        ),
    ]
