# Generated by Django 2.1.5 on 2019-02-09 14:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('whoweare', '0002_auto_20190209_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='whowearefields',
            name='fourthsectionmissionvisionvaluesdescriptionsinlist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=1503, null=True, size=3, verbose_name='Fourth Section mission vision and values descriptions in list *'),
        ),
    ]
