# Generated by Django 2.1.5 on 2019-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactpage', '0002_auto_20190205_1441'),
        ('servicespage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], default='1', max_length=500)),
                ('name', models.CharField(max_length=500, verbose_name='Nome *')),
                ('surname', models.CharField(max_length=500, verbose_name='Sobrenome *')),
                ('bday', models.DateField(verbose_name='Data de Nascimento *')),
                ('city', models.CharField(max_length=500, verbose_name='Cidade *')),
                ('neighbourhood', models.CharField(max_length=500, verbose_name='Bairro *')),
                ('age', models.IntegerField()),
                ('phonenumber', models.IntegerField(verbose_name='Telefone *')),
                ('quotation', models.FileField(upload_to='', verbose_name='Cotação *')),
                ('contact', models.ForeignKey(on_delete='CASCADE', to='contactpage.Contact')),
                ('services', models.ManyToManyField(to='servicespage.ModuleService')),
            ],
        ),
    ]
