# Generated by Django 2.1.5 on 2019-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete='CASCADE', to='contactpage.Contact'),
        ),
    ]
