# Generated by Django 2.1.5 on 2019-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190208_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Cotação *'),
        ),
    ]
