# Generated by Django 2.1.5 on 2019-02-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20190212_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
    ]
