# Generated by Django 2.1.5 on 2019-02-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0003_auto_20190208_1501'),
        ('administration', '0005_remove_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='contactpage.Contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='servicespage.ModuleService'),
        ),
    ]
