# Generated by Django 2.1.5 on 2019-02-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20190213_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, to='servicespage.ModuleService'),
        ),
    ]
