# Generated by Django 2.1.5 on 2019-02-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20190213_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
    ]
