# Generated by Django 2.1.5 on 2019-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_remove_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento *'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cidade *'),
        ),
    ]
