# Generated by Django 2.1.5 on 2019-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20190301_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CEP *'),
        ),
    ]
