# Generated by Django 2.1.5 on 2019-02-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFields',
            new_name='Contact',
        ),
    ]
