# Generated by Django 2.1.5 on 2019-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactpage', '0002_auto_20190205_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Your Phone Number (optional)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Your Web Site (optional)'),
        ),
    ]
