# Generated by Django 2.1.5 on 2019-02-06 22:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uppertitle', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=122, size=2, verbose_name='Upper title list *')),
                ('initialdescription', models.TextField(verbose_name='Initial description field *')),
                ('tabs', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=183, size=3, verbose_name='Tab title list *')),
                ('firsttabsubtitle', models.TextField(verbose_name='First tab first subtitle *')),
                ('firsttabsecondsubtitle', models.TextField(verbose_name='Firs tab second subtitle *')),
                ('firsttabdescriprion', models.TextField(verbose_name='First tab description *')),
                ('firsttabimage', models.ImageField(upload_to='', verbose_name='First tab image')),
                ('firsttabvideoURL', models.URLField(verbose_name='First tab video URL *')),
                ('secondtabsubtitle', models.TextField(verbose_name='Second tab subtitle *')),
                ('secondtabdescription', models.TextField(verbose_name='Second tab description *')),
                ('thirdtabsubtitle', models.TextField(verbose_name='Third tab subtitle *')),
                ('thirdtabdescription', models.TextField(verbose_name='Third tab description *')),
                ('thirdtablist', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=244, size=4, verbose_name='Tab title list *')),
            ],
        ),
    ]
