# Generated by Django 2.1.5 on 2019-02-13 23:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefields',
            name='uppertitle',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=162, size=2, verbose_name='Upper title list *'),
        ),
    ]
