# Generated by Django 2.1.5 on 2019-02-07 19:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimage', models.ImageField(upload_to='', verbose_name='Logo image *')),
                ('headerURLoptions', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=244, size=4, verbose_name='Header URL options list *')),
                ('headeroptions', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=244, size=4, verbose_name='Header options list *')),
            ],
        ),
    ]
