# Generated by Django 2.1.5 on 2019-02-07 22:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleService',
            fields=[
                ('module_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_title', models.TextField(verbose_name='Title of the page *')),
                ('pathlist', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='Path list *')),
                ('firstsectiontitleofservice', models.TextField(verbose_name='Title of the service *')),
                ('firstsectionfirstdescription', models.TextField(verbose_name='First description of the service *')),
                ('firstsectionseconddescription', models.TextField(verbose_name='Second description of the service *')),
                ('firstsectiionlistimage', models.ImageField(upload_to='', verbose_name='First section image *')),
                ('firstsectionimagescarousel', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=183, size=3, verbose_name='Path to the images *')),
                ('firstsectionworkslist', django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=3006, size=6, verbose_name='Works list *')),
                ('secondsectiontitle', models.TextField(verbose_name='Title of the includes of the services *')),
                ('secondsetiontitlesofservicesincludes', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='Titles of services includes *')),
                ('secondsetiondescriptionssofservicesincludes', django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=3006, size=6, verbose_name='Descriptions of services includes *')),
                ('thirdsectiontitle', models.TextField(verbose_name='Title of the how can we help you section *')),
                ('thirdsectionkindsofservicestitles', django_mysql.models.ListCharField(models.CharField(max_length=501), max_length=2515, size=5, verbose_name='Titles of kinds of services *')),
                ('thirdsectionkindsofservicesdescription', django_mysql.models.ListCharField(models.CharField(max_length=2000), max_length=10005, size=5, verbose_name='Descriptions of kinds of services *')),
                ('fourthserctiontitle', models.TextField(verbose_name='Title o the pricing options *')),
                ('fourthserctionpricingoptionstitles', django_mysql.models.ListCharField(models.CharField(max_length=60), max_length=366, size=6, verbose_name='Titles of pricing options *')),
                ('fourthserctionfirstpricingoptionprice', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3, verbose_name='Price of the first pricing option *')),
                ('fourthserctionfirstpricingoptionfeatures', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Features of the first pricing option *')),
                ('fourthserctionsecondpricingoptionprice', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3, verbose_name='Price of the second pricing option *')),
                ('fourthserctionsecondpricingoptionfeatures', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Features of the second pricing option *')),
                ('fourthserctionthirdpricingoptionprice', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3, verbose_name='Price of the third pricing option *')),
                ('fourthserctionthirdpricingoptionfeatures', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Features of the third pricing option *')),
                ('fifthsectiontitle', models.TextField(verbose_name='Global Team Title *')),
                ('fifthsectionteammembersname', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Names of the members of the global team *')),
                ('fifthsectionfirstteammemberfunctions', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='First team member functions *')),
                ('fifthsectionsecondteammemberfunctions', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Second team member functions *')),
                ('fifthsectionthirdteammemberfunctions', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Third team member functions *')),
                ('fifthsectionfourthteammemberfunctions', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=324, size=4, verbose_name='Fourth team member functions *')),
                ('sixthsectiontitle', models.TextField(verbose_name='First-class business service title *')),
                ('sixthsectiondescription', models.TextField(verbose_name='First-class business service description *')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('nameoftheservice', models.CharField(max_length=500, verbose_name='Name of the Service *')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of the service *')),
                ('category', models.CharField(choices=[('Administrative and financial services', 'Administrative and financial services'), ('Tecnology', 'Tecnology'), ('Insurance', 'Insurance')], max_length=500, verbose_name='Category of the service *')),
                ('URLtotheservice', models.URLField(verbose_name='URL to the service *')),
                ('module_service', models.ForeignKey(on_delete='CASCADE', to='servicespage.ModuleService')),
            ],
        ),
    ]
