# Generated by Django 2.1.5 on 2019-02-07 23:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionfirstpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=4, verbose_name='Features of the first pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionsecondpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=4, verbose_name='Features of the second pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionthirdpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=4, verbose_name='Features of the third pricing option *'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Serviços de Contabilidade', 'Serviços de Contabilidade'), ('Conciliação Bancária', 'Conciliação Bancária'), ('Meios de Pagamento', 'Meios de Pagamento'), ('Automação Comercial', 'Automação Comercial'), ('Seguros', 'Seguros')], max_length=500, verbose_name='Category of the service *'),
        ),
    ]
