# Generated by Django 2.1.5 on 2019-02-07 23:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0002_auto_20190207_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionfirstpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=5, verbose_name='Features of the first pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionsecondpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=5, verbose_name='Features of the second pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionthirdpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=405, size=5, verbose_name='Features of the third pricing option *'),
        ),
    ]
