# Generated by Django 2.1.5 on 2019-02-08 20:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0003_auto_20190207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectionfirstteammemberfunctions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=324, null=True, size=4, verbose_name='First team member functions *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectionfourthteammemberfunctions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=324, null=True, size=4, verbose_name='Fourth team member functions *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectionsecondteammemberfunctions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=324, null=True, size=4, verbose_name='Second team member functions *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectionteammembersname',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=324, null=True, size=4, verbose_name='Names of the members of the global team *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectionthirdteammemberfunctions',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=324, null=True, size=4, verbose_name='Third team member functions *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionfirstpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=405, null=True, size=5, verbose_name='Features of the first pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionfirstpricingoptionprice',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=63, null=True, size=3, verbose_name='Price of the first pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionpricingoptionstitles',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=366, null=True, size=6, verbose_name='Titles of pricing options *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionsecondpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=405, null=True, size=5, verbose_name='Features of the second pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionsecondpricingoptionprice',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=63, null=True, size=3, verbose_name='Price of the second pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionthirdpricingoptionfeatures',
            field=django_mysql.models.ListCharField(models.CharField(max_length=80), blank=True, max_length=405, null=True, size=5, verbose_name='Features of the third pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctionthirdpricingoptionprice',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), blank=True, max_length=63, null=True, size=3, verbose_name='Price of the third pricing option *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='fourthserctiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='Title o the pricing options *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsectiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='Title of the includes of the services *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiondescriptionssofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=3542, null=True, size=7, verbose_name='Descriptions of services includes *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiontitlesofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=462, null=True, size=7, verbose_name='Titles of services includes *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='sixthsectiondescription',
            field=models.TextField(blank=True, null=True, verbose_name='First-class business service description *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='sixthsectiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='First-class business service title *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='thirdsectionkindsofservicesdescription',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2000), blank=True, max_length=10005, null=True, size=5, verbose_name='Descriptions of kinds of services *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='thirdsectionkindsofservicestitles',
            field=django_mysql.models.ListCharField(models.CharField(max_length=501), blank=True, max_length=2515, null=True, size=5, verbose_name='Titles of kinds of services *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='thirdsectiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='Title of the how can we help you section *'),
        ),
    ]
