# Generated by Django 2.1.5 on 2019-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0004_auto_20190208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='fifthsectiontitle',
            field=models.TextField(blank=True, null=True, verbose_name='Global Team Title *'),
        ),
    ]
