# Generated by Django 2.1.5 on 2019-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0005_auto_20190208_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectiionlistimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='First section image *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionfirstdescription',
            field=models.TextField(blank=True, null=True, verbose_name='First description of the service *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionseconddescription',
            field=models.TextField(blank=True, null=True, verbose_name='Second description of the service *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectiontitleofservice',
            field=models.TextField(blank=True, null=True, verbose_name='Title of the service *'),
        ),
    ]
