# Generated by Django 2.1.5 on 2019-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0006_auto_20190208_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='URLtotheservice',
            field=models.URLField(blank=True, null=True, verbose_name='URL to the service *'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Serviços de Contabilidade', 'Serviços de Contabilidade'), ('Conciliação Bancária', 'Conciliação Bancária'), ('Meios de Pagamento', 'Meios de Pagamento'), ('Automação Comercial', 'Automação Comercial'), ('Seguros', 'Seguros')], max_length=500, null=True, verbose_name='Category of the service *'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image of the service *'),
        ),
        migrations.AlterField(
            model_name='service',
            name='module_service',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='servicespage.ModuleService'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nameoftheservice',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name of the Service *'),
        ),
    ]
