# Generated by Django 2.1.5 on 2019-02-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0007_auto_20190208_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='URLtotheservice',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL to the service *'),
        ),
    ]
