# Generated by Django 2.1.5 on 2019-02-08 23:05

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0008_auto_20190208_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionimagescarousel',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=183, null=True, size=3, verbose_name='Path to the images *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionworkslist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=3006, null=True, size=6, verbose_name='Works list *'),
        ),
    ]
