# Generated by Django 2.1.5 on 2019-02-08 23:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0009_auto_20190208_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionworkslist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=4008, null=True, size=8, verbose_name='Works list *'),
        ),
    ]
