# Generated by Django 2.1.5 on 2019-02-08 23:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0010_auto_20190208_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='thirdsectionkindsofservicesdescription',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2000), blank=True, max_length=14007, null=True, size=7, verbose_name='Descriptions of kinds of services *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='thirdsectionkindsofservicestitles',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=3507, null=True, size=7, verbose_name='Titles of kinds of services *'),
        ),
    ]
