# Generated by Django 2.1.5 on 2019-02-09 15:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0011_auto_20190208_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionworkslist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=10020, null=True, size=8, verbose_name='Works list *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiondescriptionssofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=5060, null=True, size=10, verbose_name='Descriptions of services includes *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiontitlesofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=660, null=True, size=10, verbose_name='Titles of services includes *'),
        ),
    ]
