# Generated by Django 2.1.5 on 2019-02-09 15:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0012_auto_20190209_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='firstsectionworkslist',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=10020, null=True, size=20, verbose_name='Works list *'),
        ),
    ]
