# Generated by Django 2.1.5 on 2019-02-12 22:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicespage', '0013_auto_20190209_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiondescriptionssofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=15686, null=True, size=31, verbose_name='Descriptions of services includes *'),
        ),
        migrations.AlterField(
            model_name='moduleservice',
            name='secondsetiontitlesofservicesincludes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=60), blank=True, max_length=2046, null=True, size=31, verbose_name='Titles of services includes *'),
        ),
    ]
